## TEIS Outcomes Calculation

[The Tennessee Early Intervention System (TEIS)](https://www.tn.gov/disability-and-aging/disability-aging-programs/teis.html) is a program program that offers therapy and other services to families of infants and young children with developmental delays or disabilities. 

TEIS is required to report outcomes data annually on children who exited early intervention services and received a minimum of 6 months of service. This is based on the first (entrance) assessment and last (exit) assessment. For the 2023-24 data, every exit assessment used the BDI-3, but there were three possible entrance assessments.

Your first objective in this project is to compare two sets of business rules for calculating Early Childhood Outcome (ECO). For more information on the sets of business rules, see the "TEIS Data Project" document. 

You can see the calculations for the original business rules in the ECO Data spreadsheet. Your first objective is to redo the calculations for children with either the BDI-2 or BDI-3 as the entrance assessment. See the new business rules in the TEIS Data Project document.

Your second objective is to investigate children who did not improve functioning (progress category a) and report demographic qualities of these children, including
* Point of Entry office (POE)
    - See the TEIS Acronyms and Terms document for the full for each POE
* Length of time in services
* Length between assessment and exit
* Length between entrance and exit assessments
* Difference between extrance and exit assessment instruments
* Age at assessment/exit

#### Data Overview

You've been provided several data files.

* NSS_ECO Data Ind 3 FFY 2023-24 20241211.xlsx: Contains the original data source for the 2023-24 TEIS ECO data
* NSS data_BDI3 Scores 20230101 20240630_Compiled20241107.xlsx: Contains raw BDI-3 data for recalculating outcomes data
* NSS data_BDI2_scores_20200101-20230131_20241106.csv: Contains raw BDI-2 data for recalculating outcomes data

In addition, there are a few additional documents for reference:

* TEIS Data Project – Jan. 2025.docx: Provides an overview of the project and outcome data. 
* BDI scoring resource.docx: Provides an explanation of scores on the BDI-3
* BDI3_ScoreReport Sample.pdf: A sample of BDI-3 Score Report used for training
* TEIS Acronyms and Terms.pdf: A resource document providing abbreviations commonly found in TEIS

In [2]:
import pandas as pd

In [82]:
bdi2_df = pd.read_csv('../teis-JesseCrawford89/data/NSS data_BDI2 scores_20200101-20230131_20241106.csv')

C:\Users\Jesse\AppData\Local\Temp\ipykernel_18412\2648368418.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  bdi2_df = pd.read_csv('../teis-JesseCrawford89/data/NSS data_BDI2 scores_20200101-20230131_20241106.csv')

In [6]:
bdi3_df = pd.read_excel('../teis-JesseCrawford89/data/NSS data_BDI3 Scores 20230101 20240630_Compiled_20241107.xlsx')

In [7]:
bdi_eco = pd.read_excel('../teis-JesseCrawford89/data/NSS_ECO Data Ind 3 FFY 2023-24 20241211.xlsx', sheet_name = 'ECO with Exit23-24 ')

In [84]:
entry_exit = bdi_eco[(bdi_eco['OC1 Data Check']==1)][['CHILD_ID','ECO_Entry_DATE','ECO_Exit_DATE','BDI 3\nECO_Entry_DATE','BDI 3\nECO_Exit_DATE','BDI2 Entry Date']]

In [86]:
bdi2_df['testDate'] = pd.to_datetime(bdi2_df['testDate'])
bdi3_df['Adaptive-Self Care Date of Testing'] = pd.to_datetime(bdi3_df['Adaptive-Self Care Date of Testing'])
entry_exit.rename(columns={'CHILD_ID':'TEIDS Child ID'}, inplace=True)

entry_exit

,TEIDS Child ID,ECO_Entry_DATE,ECO_Exit_DATE,BDI 3\nECO_Entry_DATE,BDI 3\nECO_Exit_DATE,BDI2 Entry Date
0,473991,2020-01-07,2022-12-27,NaT,NaT,NaT
1,474186,2020-02-13,2023-10-26,NaT,2023-10-26,NaT
2,474575,2020-01-17,2020-07-29,NaT,NaT,NaT
3,474623,2019-01-22,2022-12-16,NaT,NaT,2020-01-08
4,474848,2021-07-09,2023-08-04,NaT,2023-08-04,2021-06-22
...,...,...,...,...,...,...
7925,567392,2023-11-17,2024-10-14,2023-11-17,2024-10-14,NaT
7927,567510,2023-11-30,2024-10-02,2023-11-30,2024-10-02,NaT
7928,567756,2023-12-05,2024-09-09,2023-12-05,2024-09-09,NaT
7934,568323,2023-12-06,2024-10-01,2023-12-06,2024-10-01,NaT
7935,568536,2023-12-14,2024-08-27,2023-12-14,2024-08-27,NaT

In [64]:
bdi3_df

,Last Name,First Name,Gender,Date of Birth,Location - Root Level (PC),Location - Root Level (AH),Location - Sub Level 1,Location - Sub Level 2,Location - Sub Level 3,Child ID,...,Cognitive-Perception and Concepts RS,Cognitive-Perception and Concepts SS,Cognitive-Perception and Concepts PR,Cognitive-Perception and Concepts AE,Cognitive-Perception and Concepts RDI,Cognitive-Perception and Concepts CSS,Cognitive-Perception and Concepts CSS 90%,Cognitive-Perception and Concepts Z-Score,Cognitive-Perception and Concepts T-Score,Cognitive-Perception and Concepts NCE
0,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,Greater Nashville,NaN,NaN,474074,...,13.0,4.0,2,25,1990-01-01 00:00:00,464.0,450 - 479,2.00,30.0,8
1,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,Greater Nashville,NaN,NaN,474186,...,24.0,8.0,25,40,68/90,510.0,502 - 517,0.67,43.0,36
2,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,Upper Cumberland,NaN,NaN,474641,...,26.0,9.0,37,42,77/90,514.0,507 - 522,0.33,47.0,43
3,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,Southwest,NaN,NaN,474848,...,17.0,6.0,9,32,25/90,487.0,476 - 497,1.33,37.0,22
4,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,South Central,NaN,NaN,474967,...,12.0,3.0,1,22,1990-01-01 00:00:00,451.0,429 - 473,2.33,27.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34974,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,Memphis Delta,NaN,NaN,NaN,...,10.0,4.0,2,15,1990-02-01 00:00:00,426.0,408 - 444,2.00,30.0,8
34975,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,Southeast Tennessee,NaN,NaN,NaN,...,10.0,4.0,2,15,1990-02-01 00:00:00,426.0,408 - 444,2.00,30.0,8
34976,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,East Tennessee,NaN,NaN,NaN,...,11.0,5.0,5,18,1990-02-01 00:00:00,437.0,421 - 453,1.67,33.0,15
34977,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,First Tennessee,NaN,NaN,NaN,...,9.0,8.0,25,12,58/90,411.0,392 - 431,0.67,43.0,36
34978,NaN,NaN,NaN,NaN,NaN,Tennessee Early Intervention Sys,East Tennessee,NaN,NaN,5777288,...,12.0,8.0,25,22,66/90,451.0,429 - 473,0.67,43.0,36

In [88]:
bdi3_exit = entry_exit.merge(bdi3_df,how='right',left_on=['TEIDS Child ID','BDI 3\nECO_Exit_DATE'],right_on=['TEIDS Child ID','Adaptive-Self Care Date of Testing'])
bdi3_exit

ValueError: You are trying to merge on int64 and object columns for key 'TEIDS Child ID'. If you wish to proceed you should use pd.concat

In [72]:
print(entry_exit[['BDI 3\nECO_Entry_DATE']].dtypes)
print(bdi3_df[['Adaptive-Self Care Date of Testing']].dtypes)

BDI 3\nECO_Entry_DATE    datetime64[ns]
dtype: object
Adaptive-Self Care Date of Testing    datetime64[ns]
dtype: object

In [78]:
bdi3_entry['Student TEIDS ID'] = bdi3_entry['Student TEIDS ID'].astype('int64')
bdi3_entry = entry_exit.merge(bdi3_df,how='inner',left_on=['TEIDS Child ID','BDI 3\nECO_Entry_DATE'],right_on=['TEIDS Child ID','Adaptive-Self Care Date of Testing'])
bdi3_entry

KeyError: 'Student TEIDS ID'

In [32]:
bdi2_entry_subdomains = entry_exit.merge(bdi2_df,how='inner',left_on=['TEIDS Child ID','BDI2 Entry Date'],right_on=['Student TEIDS ID','testDate'])

bdi2_entry = bdi2_df[bdi2_df['studentAssessmentID'].isin(bdi2_entry_subdomains['studentAssessmentID'])]
bdi2_entry

,StudentID,studentAssessmentID,resultStudentDomainID,Student TEIDS ID,domainID,domainText,ScoreTypeID,ScoreTypeText,StaffExternalID,testDate,...,AESign,isSSRequired,stdDevScore1,stdDevScore2,stdDevScore3,NCESign,totalCSS,totalCSSMin,totalCSSMax,NormType
7830,1939752,7778442,123229652,474623,7,Self-Care,2.0,ItemDetails,28828.0,2020-01-08,...,NaN,1.0,NaN,NaN,NaN,<,287.0,260.0,314.0,2
7831,1939752,7778442,123229653,474623,10,Adult Interaction,2.0,ItemDetails,28828.0,2020-01-08,...,NaN,1.0,NaN,NaN,NaN,NaN,310.0,296.0,324.0,2
7832,1939752,7778442,123229654,474623,12,Self-Concept and Social Role,2.0,ItemDetails,28828.0,2020-01-08,...,NaN,1.0,NaN,NaN,NaN,<,332.0,305.0,359.0,2
7833,1939752,7778442,123229655,474623,14,Receptive Communication,2.0,ItemDetails,28828.0,2020-01-08,...,NaN,1.0,NaN,NaN,NaN,NaN,348.0,337.0,359.0,2
7834,1939752,7778442,123229656,474623,15,Expressive Communication,2.0,ItemDetails,28828.0,2020-01-08,...,NaN,1.0,NaN,NaN,NaN,NaN,288.0,267.0,309.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318228,2320591,8763117,140607939,545801,6,Adaptive,NaN,NaN,NaN,NaT,...,NaN,1.0,NaN,NaN,NaN,NaN,480.0,474.0,486.0,2
318229,2320591,8763117,140607940,545801,9,Personal-Social,NaN,NaN,NaN,NaT,...,NaN,1.0,NaN,NaN,NaN,NaN,471.0,467.0,476.0,2
318230,2320591,8763117,140607941,545801,13,Communication,NaN,NaN,NaN,NaT,...,NaN,1.0,NaN,NaN,NaN,NaN,429.0,421.0,436.0,2
318231,2320591,8763117,140607942,545801,16,Motor,NaN,NaN,NaN,NaT,...,NaN,1.0,NaN,NaN,NaN,NaN,488.0,482.0,495.0,2
318232,2320591,8763117,140607943,545801,20,Cognitive,NaN,NaN,NaN,NaT,...,NaN,1.0,NaN,NaN,NaN,NaN,456.0,449.0,463.0,2

In [34]:
bdi3_exit[(bdi3_exit['TEIDS Child ID'].isin(bdi3_entry['TEIDS Child ID']))|(bdi3_exit['TEIDS Child ID'].isin(bdi2_entry['Student TEIDS ID']))]['TEIDS Child ID']

Series([], Name: TEIDS Child ID, dtype: object)

In [60]:
bdi3_exit[(bdi3_exit['TEIDS Child ID'].isin(bdi3_entry['TEIDS Child ID']))|(bdi3_exit['TEIDS Child ID'].isin(bdi2_entry['Student TEIDS ID']))]['TEIDS Child ID']

50      486692
118     490073
122     490134
133     490333
134     490333
         ...
5683    564474
5684    564596
5685    565093
5686    565305
5687    565335
Name: TEIDS Child ID, Length: 1255, dtype: int64

In [62]:
bdi3_exit

,TEIDS Child ID,ECO_Entry_DATE,BDI 3\nECO_Entry_DATE,BDI 3\nECO_Exit_DATE,BDI2 Entry Date,Last Name,First Name,Gender,Date of Birth,Location - Root Level (PC),...,Cognitive-Perception and Concepts RS,Cognitive-Perception and Concepts SS,Cognitive-Perception and Concepts PR,Cognitive-Perception and Concepts AE,Cognitive-Perception and Concepts RDI,Cognitive-Perception and Concepts CSS,Cognitive-Perception and Concepts CSS 90%,Cognitive-Perception and Concepts Z-Score,Cognitive-Perception and Concepts T-Score,Cognitive-Perception and Concepts NCE
0,474186,2020-02-13,NaT,2023-10-26,NaT,NaN,NaN,NaN,NaN,NaN,...,24.0,8.0,25,40,68/90,510.0,502 - 517,0.67,43.0,36
1,474848,2021-07-09,NaT,2023-08-04,2021-06-22,NaN,NaN,NaN,NaN,NaN,...,17.0,6.0,9,32,25/90,487.0,476 - 497,1.33,37.0,22
2,474967,2020-01-31,NaT,2023-07-31,2020-01-07,NaN,NaN,NaN,NaN,NaN,...,12.0,3.0,1,22,1990-01-01 00:00:00,451.0,429 - 473,2.33,27.0,1
3,475636,2020-09-03,NaT,2023-07-19,NaT,NaN,NaN,NaN,NaN,NaN,...,8.0,1.0,<1,8,<1/90,395.0,376 - 415,3.00,20.0,<1
4,475907,2020-02-20,NaT,2023-11-15,2020-01-17,NaN,NaN,NaN,NaN,NaN,...,11.0,1.0,<1,18,<1/90,437.0,421 - 453,3.00,20.0,<1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5683,564474,2023-10-09,2023-10-09,2024-05-07,NaT,NaN,NaN,NaN,NaN,NaN,...,5.0,1.0,<1,5,<1/90,370.0,355 - 386,3.00,20.0,<1
5684,564596,2023-10-26,2023-10-26,2024-05-10,NaT,NaN,NaN,NaN,NaN,NaN,...,16.0,9.0,37,31,73/90,482.0,471 - 493,0.33,47.0,43
5685,565093,2023-10-18,2023-10-18,2024-04-08,NaT,NaN,NaN,NaN,NaN,NaN,...,16.0,9.0,37,31,73/90,482.0,471 - 493,0.33,47.0,43
5686,565305,2023-10-23,2023-10-23,2024-05-30,NaT,NaN,NaN,NaN,NaN,NaN,...,22.0,12.0,75,39,97/90,505.0,497 - 513,0.67,57.0,64
5687,565335,2023-10-17,2023-10-17,2024-05-20,NaT,NaN,NaN,NaN,NaN,NaN,...,8.0,1.0,<1,8,<1/90,395.0,376 - 415,3.00,20.0,<1

In [14]:
bdi2_df = pd.read_csv('../data/NSS data_BDI2 scores_20200101-20230131_20241106.csv')

bdi2_df['testDate'] = pd.to_datetime(bdi2_df['testDate'])

bdi3_df = pd.read_excel('../data/NSS data_BDI3 Scores 20230101 20240630_Compiled_20241107.xlsx')

bdi3_df['Adaptive-Self Care Date of Testing'] = pd.to_datetime(bdi3_df['Adaptive-Self Care Date of Testing'])

eco_df = pd.read_excel('../data/NSS_ECO Data Ind 3 FFY 2023-24 20241211.xlsx',sheet_name='ECO with Exit23-24 ')

entry_exit = eco_df[(eco_df['OC1 Data Check']==1)][['CHILD_ID','ECO_Entry_DATE','ECO_Exit_DATE','BDI 3\nECO_Entry_DATE','BDI 3\nECO_Exit_DATE','BDI2 Entry Date']]

entry_exit.rename(columns={'CHILD_ID':'TEIDS Child ID'}, inplace=True)

bdi3_exit = entry_exit.merge(bdi3_df,how='inner',left_on=['TEIDS Child ID','BDI 3\nECO_Exit_DATE'],right_on=['TEIDS Child ID','Adaptive-Self Care Date of Testing'])

bdi3_entry = entry_exit.merge(bdi3_df,how='inner',left_on=['TEIDS Child ID','BDI 3\nECO_Entry_DATE'],right_on=['TEIDS Child ID','Adaptive-Self Care Date of Testing'])

bdi2_entry_subdomains = entry_exit.merge(bdi2_df,how='inner',left_on=['TEIDS Child ID','BDI2 Entry Date'],right_on=['Student TEIDS ID','testDate'])

bdi2_entry = bdi2_df[bdi2_df['studentAssessmentID'].isin(bdi2_entry_subdomains['studentAssessmentID'])]

## Age at assessment/exit

In [84]:
time_in_program = bdi_eco[['CHILD_ID','Days btw Initial and Exit','Days btw I-IFSP to Exit ECO','<Calc> Entrance Age (months)']]

In [86]:
time_in_program

,CHILD_ID,Days btw Initial and Exit,Days btw I-IFSP to Exit ECO,<Calc> Entrance Age (months)
0,473991,1340,1085,47
1,474186,1388,1381,48
2,474575,1327,194,46
3,474623,1338,1059,46
4,474848,887,756,49
...,...,...,...,...
9994,579717,7,-45441,12
9995,579729,17,-45456,36
9996,580243,11,-45460,19
9997,580375,8,-45448,26
9998,580840,0,-45447,3

In [111]:
time_in_program = time_in_program[time_in_program['Days btw Initial and Exit'] > 181]

In [113]:
time_in_program.loc[:, 'Years btw Initial and Exit'] = time_in_program['Days btw Initial and Exit'] / 365.2422
time_in_program.loc[:, 'Years btw I-IFSP to Exit ECO'] = time_in_program['Days btw I-IFSP to Exit ECO'] / 365.2422
time_in_program.loc[:, 'Age upon Exit (years)'] = (
    (time_in_program['<Calc> Entrance Age (months)']/12) + time_in_program['Years btw Initial and Exit']
)

In [115]:
time_in_program

,CHILD_ID,Days btw Initial and Exit,Days btw I-IFSP to Exit ECO,<Calc> Entrance Age (months),Years btw Initial and Exit,Years btw I-IFSP to Exit ECO,Age upon Exit (years)
0,473991,1340,1085,47,3.668798,2.970632,7.585465
1,474186,1388,1381,48,3.800218,3.781053,7.800218
2,474575,1327,194,46,3.633206,0.531154,7.466539
3,474623,1338,1059,46,3.663323,2.899446,7.496656
4,474848,887,756,49,2.428526,2.069859,6.511859
...,...,...,...,...,...,...,...
7939,569165,182,-45308,39,0.498299,-124.049193,3.748299
7940,569195,202,-45309,39,0.553058,-124.051930,3.803058
7941,569207,210,-45302,39,0.574961,-124.032765,3.824961
7942,569218,211,-45300,39,0.577699,-124.027289,3.827699
7943,570233,182,-45328,38,0.498299,-124.103951,3.664966

In [117]:
exit_age = time_in_program[['CHILD_ID','Age upon Exit (years)']]

In [119]:
exit_age['CHILD_ID'].isin

     CHILD_ID  Age upon Exit (years)
0      473991               7.585465
1      474186               7.800218
2      474575               7.466539
3      474623               7.496656
4      474848               6.511859
...       ...                    ...
7939   569165               3.748299
7940   569195               3.803058
7941   569207               3.824961
7942   569218               3.827699
7943   570233               3.664966

[7944 rows x 2 columns]

In [106]:
bdi2_df1 = bdi2_df[~bdi2_df['Student TEIDS ID'].isnull()]
    # there are ids that have mulitple duplicate IDs example:526857
    #the following code will help deal with duplciate domain - allowing us to create more that 1 row if it has dup domain text
bdi2_df1 = bdi2_df1.sort_values(['Student TEIDS ID','domainText']).reset_index(drop=True)
    #sequential number to each row within a group
bdi2_df1['row_number'] = bdi2_df1.groupby(['Student TEIDS ID', 'domainText']).cumcount()
    #pivot dataframe
bdi2_df1_pivot = bdi2_df1.pivot_table(index=['Student TEIDS ID', 'row_number']
              , columns='domainText'
              , values=['rawScore','DQScore','ZScore']
              , aggfunc='first')
    #flatten multi-index columns
bdi2_df1_pivot.columns = [f"{col[1]}-{col[0]}" for col in bdi2_df1_pivot.columns]
    #reset index
bdi2_df1_pivot = bdi2_df1_pivot.reset_index()
    #drop row number
bdi2_df1_pivot = bdi2_df1_pivot.drop(columns=['row_number'])
print(bdi2_df1_pivot)

      Student TEIDS ID  Adaptive-DQScore  Cognitive-DQScore  \
0                52101              80.0               97.0
1               416571              65.0               66.0
2               419105              95.0               77.0
3               419833             105.0              104.0
4               423227              65.0               59.0
...                ...               ...                ...
17688           571437              90.0               88.0
17689           580447              60.0               83.0
17690           580709              70.0               68.0
17691           650159              93.0               84.0
17692          xxxxxxx              90.0              100.0

       Communication-DQScore  Motor-DQScore  Personal-Social-DQScore  \
0                       73.0           95.0                    115.0
1                       70.0           91.0                     67.0
2                       85.0          107.0                     75.0
3                      130.0          119.0                     90.0
4                       55.0           82.0                     60.0
...                      ...            ...                      ...
17688                   85.0           95.0                     77.0
17689                   84.0           78.0                     78.0
17690                   65.0           81.0                     65.0
17691                   88.0           98.0                     92.0
17692                   84.0          100.0                    103.0

       Adaptive-ZScore  Adult Interaction-ZScore  Attention and Memory-ZScore  \
0                -1.33                      1.67                        -0.33
1                -2.33                     -1.67                        -2.00
2                -0.33                     -0.67                        -1.00
3                 0.33                     -0.33                         0.67
4                -2.33                     -3.00                        -2.33
...                ...                       ...                          ...
17688            -0.67                     -2.00                        -0.67
17689            -2.67                     -0.67                        -1.00
17690            -2.00                     -2.67                        -2.33
17691            -0.47                      0.33                        -1.00
17692            -0.67                      1.00                         0.00

       Cognitive-ZScore  ...  Peer Interaction-rawScore  \
0                 -0.20  ...                        NaN
1                 -2.27  ...                        8.0
2                 -1.53  ...                        6.0
3                  0.27  ...                        8.0
4                 -2.73  ...                        4.0
...                 ...  ...                        ...
17688             -0.80  ...                        9.0
17689             -1.13  ...                        NaN
17690             -2.13  ...                       14.0
17691             -1.07  ...                        4.0
17692              0.00  ...                        NaN

       Perception and Concepts-rawScore  Perceptual Motor-rawScore  \
0                                   5.0                        NaN
1                                  14.0                       15.0
2                                  18.0                       20.0
3                                  24.0                       20.0
4                                  12.0                       14.0
...                                 ...                        ...
17688                              14.0                       16.0
17689                               3.0                        NaN
17690                              12.0                       12.0
17691                              13.0                       14.0
17692                              12.0                        NaN

       Personal Responsibility-rawScore  Personal-Social-rawScore  \
0                                   NaN                      20.0
1                                   1.0                      65.0
2                                   7.0                      82.0
3                                  10.0                      97.0
4                                   0.0                      38.0
...                                 ...                       ...
17688                              10.0                      57.0
17689                               NaN                       6.0
17690                               4.0                      56.0
17691                               8.0                      74.0
17692                               NaN                      45.0

       Reasoning and Academic Skills-rawScore  \
0                                         NaN
1                                         8.0
2                                        10.0
3                                        12.0
4                                         4.0
...                                       ...
17688                                    10.0
17689                                     NaN
17690                                    12.0
17691                                     9.0
17692                                     NaN

       Receptive Communication-rawScore  Screener Test Total Score-rawScore  \
0                                   4.0                                 NaN
1                                  27.0                                 NaN
2                                  32.0                                 NaN
3                                  41.0                                 NaN
4                                  22.0                                 NaN
...                                 ...                                 ...
17688                              26.0                                 NaN
17689                               5.0                                 NaN
17690                              20.0                                 NaN
17691                              26.0                                 NaN
17692                              17.0                                 NaN

       Self-Care-rawScore  Self-Concept and Social Role-rawScore
0                     2.0                                    6.0
1                    32.0                                   20.0
2                    46.0                                   32.0
3                    47.0                                   44.0
4                    32.0                                   14.0
...                   ...                                    ...
17688                26.0                                   18.0
17689                 0.0                                    1.0
17690                31.0                                   12.0
17691                30.0                                   27.0
17692                22.0                                   13.0

[17693 rows x 43 columns]

In [ ]:
bdi2_df_test = transform_data(bdi2_entry)

In [ ]:
  df = file #This was originally where you would read in the csv for bdi-2, I changed it to run the already filtered dataframe -- Ryan
        #drop null student ID if you have any
df = df[~df['Student TEIDS ID'].isnull()]
    # there are ids that have mulitple duplicate IDs example:526857
    #the following code will help deal with duplciate domain - allowing us to create more that 1 row if it has dup domain text
df = df.sort_values(['Student TEIDS ID','domainText']).reset_index(drop=True)
    #sequential number to each row within a group
df['row_number'] = df.groupby(['Student TEIDS ID', 'domainText']).cumcount()
    #pivot dataframe
df_pivot = df.pivot_table(index=['Student TEIDS ID', 'row_number']
              , columns='domainText'
              , values=['rawScore','DQScore','ZScore']
              , aggfunc='first')
    #flatten multi-index columns
df_pivot.columns = [f"{col[1]}-{col[0]}" for col in df_pivot.columns]
    #reset index
df_pivot = df_pivot.reset_index()
    #drop row number
df_pivot = df_pivot.drop(columns=['row_number'])
return df_pivot

bdi2_df_test = transform_data(bdi2_entry)

In [108]:
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "30327db0-e6ca-4e48-a575-5b02b074d98f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "8af693c5-555d-4955-9523-d867dc4b13bc",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "bdi2_df = pd.read_csv('../data/NSS data_BDI2 scores_20200101-20230131_20241106.csv')\n",
    "\n",
    "bdi2_df['testDate'] = pd.to_datetime(bdi2_df['testDate'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "7ec6d930-15ad-49be-9056-7a0c77bdb4bd",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "bdi3_df = pd.read_excel('../data/NSS data_BDI3 Scores 20230101 20240630_Compiled_20241107.xlsx')\n",
    "\n",
    "bdi3_df['Adaptive-Self Care Date of Testing'] = pd.to_datetime(bdi3_df['Adaptive-Self Care Date of Testing'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "71525fb5-3917-4c29-90a5-687ff2474770",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "eco_df = pd.read_excel('../data/NSS_ECO Data Ind 3 FFY 2023-24 20241211.xlsx',sheet_name='ECO with Exit23-24 ')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "0d7bc4da-df2c-4409-b260-568312e24ed0",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "entry_exit = eco_df[(eco_df['OC1 Data Check']==1)][['CHILD_ID','BDI 3\\nECO_Entry_DATE','BDI 3\\nECO_Exit_DATE','BDI2 Entry Date']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "b1135c0f-6639-4a29-9644-943cb0fe97e3",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "entry_exit.rename(columns={'CHILD_ID':'TEIDS Child ID'}, inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "c1cade8b-43ae-4344-a526-eaf7a61eb030",
   "metadata": {},
   "outputs": [],
   "source": [
    "entry_exit = entry_exit[(entry_exit['BDI 3\\nECO_Exit_DATE'].notnull())&((entry_exit['BDI 3\\nECO_Entry_DATE'].notnull())|(entry_exit['BDI2 Entry Date'].notnull()))]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "15117de2-06f6-485d-b4f2-b5bfe69e47a6",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "bdi3_exit = entry_exit.merge(bdi3_df,how='inner',left_on=['TEIDS Child ID','BDI 3\\nECO_Exit_DATE'],right_on=['TEIDS Child ID','Adaptive-Self Care Date of Testing'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "583a501f-f056-4462-978d-39e9cc8214e5",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "bdi3_entry = entry_exit.merge(bdi3_df,how='inner',left_on=['TEIDS Child ID','BDI 3\\nECO_Entry_DATE'],right_on=['TEIDS Child ID','Adaptive-Self Care Date of Testing'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "34e98cd6-81c9-4895-bbf2-a91696782be5",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "bdi2_entry_subdomains = entry_exit.merge(bdi2_df,how='inner',left_on=['TEIDS Child ID','BDI2 Entry Date'],right_on=['Student TEIDS ID','testDate'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "bae9bc4b-ec53-4dd1-83d7-d31488aa231f",
   "metadata": {},
   "outputs": [],
   "source": [
    "bdi2_entry_subdomains = bdi2_entry_subdomains[~bdi2_entry_subdomains['testDate'].isnull()]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "5b1f8d21-ebdd-4df5-9e52-f2fa7b5f42a9",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "bdi2_entry = bdi2_df[bdi2_df['studentAssessmentID'].isin(bdi2_entry_subdomains['studentAssessmentID'])]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "2f47f55d-7ad5-4d40-9a4a-9f9a82af8d2e",
   "metadata": {},
   "outputs": [],
   "source": [
    "bdi2_entry['Student TEIDS ID'] = bdi2_entry['Student TEIDS ID'].astype('int64')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "d6647693-f597-417e-be5f-4d0a986414eb",
   "metadata": {},
   "outputs": [],
   "source": [
    "bdi3_entry = bdi3_entry[~bdi3_entry['Adaptive-Self Care Date of Testing'].isnull()]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "814c3930-8f68-4c15-83bf-6104411e2e4a",
   "metadata": {},
   "outputs": [],
   "source": [
    "bdi2_entry = bdi2_entry[['Student TEIDS ID','domainText','rawScore','DQScore','ZScore']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "2dbd3af3-e1ec-4284-b59d-1fc87bd7b91e",
   "metadata": {},
   "outputs": [],
   "source": [
    "bdi3_entry = bdi3_entry[['TEIDS Child ID','Adaptive Developmental Quotient','Social-Emotional Developmental Quotient','Communication Developmental Quotient','Motor Developmental Quotient','Cognitive Developmental Quotient','Adaptive-Self Care RS','Adaptive-Self Care Z-Score','Adaptive-Personal Responsibility RS','Adaptive-Personal Responsibility Z-Score','Social Emotional-Adult Interaction RS','Social Emotional-Adult Interaction Z-Score','Social Emotional-Peer Interaction RS','Social Emotional-Peer Interaction Z-Score','Social Emotional-Self Concept / Social Role RS','Social Emotional-Self Concept / Social Role Z-Score','Communication-Receptive Communication RS','Communication-Receptive Communication Z-Score','Communication-Expressive Communication RS','Communication-Expressive Communication Z-Score','Motor-Gross Motor RS','Motor-Gross Motor Z-Score','Motor-Fine Motor RS','Motor-Fine Motor Z-Score','Motor-Perceptual Motor RS','Motor-Perceptual Motor Z-Score','Cognitive-Attention and Memory RS','Cognitive-Attention and Memory Z-Score','Cognitive-Reasoning / Academic Skills RS','Cognitive-Reasoning / Academic Skills Z-Score','Cognitive-Perception and Concepts RS','Cognitive-Perception and Concepts Z-Score']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "ba381218-c258-4d02-98d9-ea6c3fb439fc",
   "metadata": {},
   "outputs": [],
   "source": [
    "bdi3_exit = bdi3_exit[['TEIDS Child ID','Adaptive Developmental Quotient','Social-Emotional Developmental Quotient','Communication Developmental Quotient','Motor Developmental Quotient','Cognitive Developmental Quotient','Adaptive-Self Care RS','Adaptive-Self Care Z-Score','Adaptive-Personal Responsibility RS','Adaptive-Personal Responsibility Z-Score','Social Emotional-Adult Interaction RS','Social Emotional-Adult Interaction Z-Score','Social Emotional-Peer Interaction RS','Social Emotional-Peer Interaction Z-Score','Social Emotional-Self Concept / Social Role RS','Social Emotional-Self Concept / Social Role Z-Score','Communication-Receptive Communication RS','Communication-Receptive Communication Z-Score','Communication-Expressive Communication RS','Communication-Expressive Communication Z-Score','Motor-Gross Motor RS','Motor-Gross Motor Z-Score','Motor-Fine Motor RS','Motor-Fine Motor Z-Score','Motor-Perceptual Motor RS','Motor-Perceptual Motor Z-Score','Cognitive-Attention and Memory RS','Cognitive-Attention and Memory Z-Score','Cognitive-Reasoning / Academic Skills RS','Cognitive-Reasoning / Academic Skills Z-Score','Cognitive-Perception and Concepts RS','Cognitive-Perception and Concepts Z-Score']]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "2bd98464-c290-498c-9ed4-fdca3f19b0e0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Dibran wrote this, don't praise me. -- Ryan\n",
    "def transform_data(file)-> pd.DataFrame:\n",
    "    df = file #This was originally where you would read in the csv for bdi-2, I changed it to run the already filtered dataframe -- Ryan\n",
    "        #drop null student ID if you have any\n",
    "    df = df[~df['Student TEIDS ID'].isnull()]\n",
    "    # there are ids that have mulitple duplicate IDs example:526857\n",
    "    #the following code will help deal with duplciate domain - allowing us to create more that 1 row if it has dup domain text\n",
    "    df = df.sort_values(['Student TEIDS ID','domainText']).reset_index(drop=True)\n",
    "    #sequential number to each row within a group\n",
    "    df['row_number'] = df.groupby(['Student TEIDS ID', 'domainText']).cumcount()\n",
    "    #pivot dataframe\n",
    "    df_pivot = df.pivot_table(index=['Student TEIDS ID', 'row_number']\n",
    "              , columns='domainText'\n",
    "              , values=['rawScore','DQScore','ZScore']\n",
    "              , aggfunc='first')\n",
    "    #flatten multi-index columns\n",
    "    df_pivot.columns = [f\"{col[1]}-{col[0]}\" for col in df_pivot.columns]\n",
    "    #reset index\n",
    "    df_pivot = df_pivot.reset_index()\n",
    "    #drop row number\n",
    "    df_pivot = df_pivot.drop(columns=['row_number'])\n",
    "    return df_pivot"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "dc451f27-b031-4b20-b4e7-f2e0063f2bf3",
   "metadata": {},
   "outputs": [],
   "source": [
    "bdi2_df_test = transform_data(bdi2_entry)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "0354f8d6-d439-4884-82ed-e2568ec2e768",
   "metadata": {},
   "outputs": [],
   "source": [
    "test_ids = bdi3_exit[(bdi3_exit['TEIDS Child ID'].isin(bdi3_entry['TEIDS Child ID']))|(bdi3_exit['TEIDS Child ID'].isin(bdi2_entry['Student TEIDS ID']))]['TEIDS Child ID']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "2a90deeb-5d40-4a5e-96f4-7533e75ee8e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "test_ids"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "83c5d8ba-b46d-40b2-8e3d-f1f5cc69445d",
   "metadata": {},
   "outputs": [],
   "source": [
    "#(bdi3_exit[(bdi3_exit['TEIDS Child ID'].isin(bdi3_entry['TEIDS Child ID']))|(bdi3_exit['TEIDS Child ID'].isin(bdi2_entry['Student TEIDS ID']))]['TEIDS Child ID']).to_csv('TEIDS Child IDs',index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "0f3de5c3-3aea-4d96-9a87-030aa9827de7",
   "metadata": {},
   "outputs": [],
   "source": [
    "bdi2_flag = pd.DataFrame({'TEIDS Child ID':bdi2_entry['Student TEIDS ID'].unique()})\n",
    "bdi2_flag['bdi_flag'] = 2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "5bef0338-8c68-4d86-9054-6c0a9c45ed65",
   "metadata": {},
   "outputs": [],
   "source": [
    "bdi3_flag = pd.DataFrame(bdi3_entry['TEIDS Child ID'])\n",
    "bdi3_flag['bdi_flag'] = 3"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "9dddec05-020d-4856-9fb0-018e9cf10873",
   "metadata": {},
   "outputs": [],
   "source": [
    "entry_flag = bdi2_flag.merge(bdi3_flag,how='outer',left_on=['TEIDS Child ID','bdi_flag'],right_on=['TEIDS Child ID','bdi_flag'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "5c7fb4b5-3b2d-40df-a88c-9fe075ef9700",
   "metadata": {},
   "outputs": [],
   "source": [
    "entry_flag"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "56f129b2-160a-4fdb-a778-53c7c30dc40b",
   "metadata": {},
   "outputs": [],
   "source": [
    "exit_flagged = entry_flag.merge(bdi3_exit,how='inner',on='TEIDS Child ID')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "9cfcb348-e65c-4625-97c2-1ed7eb9abd8c",
   "metadata": {},
   "outputs": [],
   "source": [
    "bdi2_entry_exit = exit_flagged[exit_flagged['bdi_flag']==2]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "90587413-4d53-45c7-a8eb-4a6668dfc6c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "bdi3_entry_exit = exit_flagged[exit_flagged['bdi_flag']==3]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "5a3fac0c-ad0e-4611-a29a-a90da3c99406",
   "metadata": {},
   "outputs": [],
   "source": [
    "#domains = pd.DataFrame({'Adaptive':['Self-Care','Personal Responsibility'],'Social-Emotional':['Adult Interaction','Peer Interaction','Self-Concept and Social Role'],'Communication':['Receptive Communication','Expressive Communication'],'Motor':['Gross Motor','Fine Motor','Perceptual Motor'],'Cognitive':['Attention and Memory','Reasoning and Academic Skills','Perception and Concepts']})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "a4f27774-1e20-42a0-8d17-98f1d98513cc",
   "metadata": {},
   "outputs": [],
   "source": [
    "#OC1 = ['*Social-Emotional*','*Personal-Social*','*Adult Interaction*','*Peer Interaction*','*Self-Concept and Social Role*','*Self Concept / Social Role*']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "20e2559f-ebc6-43b1-8cb3-eafe971d3a0e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}

NameError: name 'true' is not defined